name: kw_express_pfe
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.4
  firebase_core: ^1.4.0
  rename: ^1.3.1
  firebase_auth: ^3.0.0
  provider: ^5.0.0
  cloud_firestore: ^2.4.0
  logging: ^1.0.1
  firebase_storage: ^10.0.1
  uuid: 3.0.4
  sn_progress_dialog: ^1.0.2
  font_awesome_flutter: ^9.1.0
  bordered_text: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  readmore: ^2.1.0
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  get_time_ago: ^1.0.3
  cloud_functions: ^3.0.0
  path_provider: ^2.0.2
  image_gallery_saver: ^1.6.9
  fluttertoast: ^8.0.1-nullsafety.0
  flutter_native_splash: ^1.2.1
  path: ^1.8.0
  date_time_picker: ^2.1.0
  url_launcher: ^6.0.9
  multi_image_picker2: ^5.0.2
  image_picker: ^0.8.2
  intl: ^0.17.0
  ndialog: ^4.1.0
  syncfusion_flutter_sliders: ^19.2.59
  image_cropper: ^1.4.1
  liquid_swipe: ^2.1.0
  multi_select_flutter: ^4.0.0
  photofilters: ^3.0.1
  pull_to_refresh: ^2.0.0
  flutter_exif_rotation: ^0.4.1
  flutter_image_compress: ^1.1.0
  flutter_screenutil: ^5.0.1+2
  flutter_svg: ^1.0.0
  geolocator: ^7.3.0
  geocode: ^1.0.1
  lint: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/drawable/resto_building.svg
    - assets/drawable/resto_profile.svg
    - assets/drawable/resto_offre.svg
    - assets/drawable/kw.svg
    - assets/drawable_png/
    - assets/drawable_png/client.jpg
    - assets/drawable_png/restaurent.jpg
    - assets/drawable/
    - assets/drawable/facebook.svg
    - assets/drawable/gmail.svg
    - assets/drawable/kw.svg
    - assets/drawable/logo.svg
    - assets/drawable/viber.svg
    - assets/icons/
    - assets/icon_app.png
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CedarvilleCursive-Regular
      fonts:
        - asset: assets/fonts/CedarvilleCursive-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
