const String BackgroundImage = 'assets/drawable_png/bg.png';
const String splash_screen = 'assets/drawable_png/splash_screen.png';
const String whiteLogo = 'assets/drawable_png/white-logoo.png';
const String iconFBsvg = 'assets/drawable/facebook.svg';
const String iconGMsvg = 'assets/drawable/gmail.svg';
const String iconKWsvg = 'assets/drawable/tbl.svg'; // kw.svg
const String iconKWpng = 'assets/drawable_png/tbl.png';
const String iconLogosvg = 'assets/drawable/logo.svg';
const String iconVIBERsvg = 'assets/drawable/viber.svg';
const String uploadPicture = 'assets/drawable_png/club_upload_picture.png';
